name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package application
        run: |
          zip -r my-app.zip . -x "*.git*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOYACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETDEPLOY_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Upload to S3
        run: |
          aws s3 cp my-app.zip s3://tayoacebucket/


    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: Use Node.js ${{ matrix.node-version }}
          cache: 'npm' 

      - name: Install dependencies
        run: npm install
        
      - name: Use MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.node-version }}
          cache: 'npm' 

       - name: Run Tests
        run: npm test

  deploy:
    needs: create deployment
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOYACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETDEPLOY_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy to EC2 via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name TTcode \
            --deployment-group-name Tayoaceproduction \
            --s3-location bucket=tayoacebucket,key=my-app.zip,bundleType=zip


